plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
    id 'me.modmuss50.mod-publish-plugin'
}

repositories {
    maven { url = 'https://cursemaven.com' }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    runtimeOnly "curse.maven:modmenu-308702:7808230"
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

publishMods {
    file = jar.archiveFile
    changelog = "Release for Minecraft ${minecraft_version}"
    type = STABLE
    displayName = "${mod_id}-${minecraft_version}-Fabric-${version}"
    modLoaders.add("fabric")

    curseforge {
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
                .orElse(provider { rootProject.ext.curseforgeToken })
        projectId = "1264423"
        minecraftVersions.add("${minecraft_version}")
        javaVersions.add(JavaVersion.VERSION_25)
    }

    modrinth {
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
                .orElse(provider { rootProject.ext.modrinthToken })
        projectId = "OfKzpbRU"
        minecraftVersions.add("${minecraft_version}")
    }
}

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}
